apiVersion: v1
kind: Service
metadata:
  name: kube-state-graph-frontend
spec:
  type: ClusterIP
  selector:
    app: kube-state-graph-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
